Updated CI jobs for main branch

diff --git a/.github/workflows/hello_video_vsi.yml b/.github/workflows/hello_video_vsi.yml
--- a/.github/workflows/hello_video_vsi.yml
+++ b/.github/workflows/hello_video_vsi.yml
@@ -4,11 +4,11 @@ on:
   workflow_dispatch:
 
   pull_request:
-    branches: [update-rte]
+    branches: [main]
     paths:
       - hello_video_vsi/**
   push:
-    branches: [update-rte]
+    branches: [main]
     paths:
      - hello_video_vsi/**
 
@@ -18,6 +18,7 @@ on:
 jobs:
   CI:
     strategy:
+      fail-fast: false
       matrix:
 
         compiler: [
@@ -26,8 +27,8 @@ jobs:
         ]
 
         target: [
-          {type: Corstone_300,  model: FVP_Corstone_SSE-300,  board: mps3_board},
           {type: Corstone_310,  model: FVP_Corstone_SSE-310,  board: mps3_board},
+          {type: Corstone_300,  model: FVP_Corstone_SSE-300,  board: mps3_board},
         ]
 
         build: [
@@ -68,7 +69,14 @@ jobs:
             cbuild hello_video_vsi.csolution.yml --packs --rebuild \
                 --context hello_video_vsi.${{ matrix.build.type }}+${{ matrix.target.type }} \
                 --toolchain ${{ matrix.compiler.name }} \
-                | tee hello_video_vsi.${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}.build.log
+                --log hello_video_vsi.${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}.build.log
+
+            if [ $? -eq 0 ]; then
+               echo "Build succeeded"
+            else 
+               echo "Build failed"
+               exit 1
+            fi
 
       # ----------------------------------------------------------------
       # Upload build log
