fixing exit code

diff --git a/.github/workflows/hello_vsi.yml b/.github/workflows/hello_vsi.yml
--- a/.github/workflows/hello_vsi.yml
+++ b/.github/workflows/hello_vsi.yml
@@ -75,9 +75,10 @@ jobs:
                 | tee hello_vsi.${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}.build.log
             if [ $? -eq 0 ]
             then 
-                 exit 1
+               echo "Command succeeded"
             else 
-                 exit 0
+               echo "Command failed"
+               exit 1
             fi
       # ----------------------------------------------------------------
       # Upload build log
