Added support for CS320

diff --git a/.github/workflows/hello_vsi.yml b/.github/workflows/hello_vsi.yml
--- a/.github/workflows/hello_vsi.yml
+++ b/.github/workflows/hello_vsi.yml
@@ -4,11 +4,11 @@ on:
   workflow_dispatch:
 
   pull_request:
-    branches: [main]
+    branches: [update-rte]
     paths:
       - hello_vsi/**
   push:
-    branches: [main]
+    branches: [update-rte]
     paths:
      - hello_vsi/**
 
@@ -18,6 +18,7 @@ on:
 jobs:
   CI:
     strategy:
+      fail-fast: false
       matrix:
 
         compiler: [
@@ -26,9 +27,10 @@ jobs:
         ]
 
         target: [
-          {type: Corstone_300,  model: FVP_Corstone_SSE-300,  board: mps3_board},
+          {type: Corstone_320,  model: FVP_Corstone_SSE-320,  board: mps4_board},
+          {type: Corstone_315,  model: FVP_Corstone_SSE-315,  board: mps4_board},
           {type: Corstone_310,  model: FVP_Corstone_SSE-310,  board: mps3_board},
-          {type: Corstone_315,  model: FVP_Corstone_SSE-315,  board: mps4_board}
+          {type: Corstone_300,  model: FVP_Corstone_SSE-300,  board: mps3_board}
         ]
 
         build: [
@@ -66,13 +68,20 @@ jobs:
         working-directory: ./hello_vsi
         run: |
             echo "Building Arm Virtual Hardware hello_vsi example with ${{ matrix.compiler.name }} by using the build-type ${{ matrix.build.type }} and the target type ${{ matrix.target.type }}..."
-
-            cbuild hello_vsi.csolution.yml --packs --rebuild \
+            cpackget update-index
+            cbuild hello_vsi.csolution.yml --packs --rebuild --verbose \
                 --context hello_vsi.${{ matrix.build.type }}+${{ matrix.target.type }} \
                 --toolchain ${{ matrix.compiler.name }} \
-                | tee hello_vsi.${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}.build.log
+                --log hello_vsi.${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}.build.log
 
-     # ----------------------------------------------------------------
+            if [ $? -eq 0 ]; then
+               echo "Build succeeded"
+            else 
+               echo "Build failed"
+               exit 1
+            fi
+
+      # ----------------------------------------------------------------
       # Upload build log
       # ----------------------------------------------------------------
       - name: Upload build log for context .${{ matrix.build.type }}+${{ matrix.target.type }}_${{ matrix.compiler.name }}
